-- MySQL Script generated by MySQL Workbench
-- 02/01/15 01:02:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Plebeia_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Plebeia_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Plebeia_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Plebeia_db` ;

-- -----------------------------------------------------
-- Table `Plebeia_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plebeia_db`.`User` (
  `idUser` INT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(100) NULL,
  `UserType` VARCHAR(100) NULL,
  `UserImage` VARCHAR(255) NOT NULL,
  `UserPassword` VARCHAR(255) NULL,
  `UserLogin` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plebeia_db`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plebeia_db`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `PostName` VARCHAR(100) NULL,
  `PostCategory` VARCHAR(100) NULL,
  `PostSlug` VARCHAR(255) NULL,
  `PostCover` VARCHAR(255) NULL,
  `PostDate` DATE NULL,
  `PostResumo` VARCHAR(255) NULL,
  `PostContent` LONGTEXT NULL,
  PRIMARY KEY (`idPost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plebeia_db`.`PostGallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plebeia_db`.`PostGallery` (
  `idPostGallery` INT NOT NULL AUTO_INCREMENT,
  `PostGalleryName` VARCHAR(255) NULL,
  `PostGalleryTitle` VARCHAR(100) NULL,
  `Post_idPost` INT NOT NULL,
  PRIMARY KEY (`idPostGallery`),
  INDEX `fk_PostGallery_Post_idx` (`Post_idPost` ASC),
  CONSTRAINT `fk_PostGallery_Post`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `Plebeia_db`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plebeia_db`.`Partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plebeia_db`.`Partners` (
  `idPartners` INT NOT NULL AUTO_INCREMENT,
  `PartnersName` VARCHAR(100) NULL,
  `PartnersCover` VARCHAR(255) NULL,
  PRIMARY KEY (`idPartners`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
